name: x_obese
description: "A new fitness app for obese"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^5.0.0-release-candidate-9.3.2
  toastification: ^3.0.1
  fluttertoast: ^8.2.12
  geolocator: ^14.0.0
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.0+1
  geocoding: ^3.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  http: ^1.3.0
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  smooth_page_indicator: ^1.2.1
  hive_flutter: ^1.1.0
  pinput: ^5.0.1
  google_maps_flutter: ^2.10.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  fluentui_system_icons: ^1.1.273
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.71.0
  carousel_slider: ^5.0.0
  flutter_secure_storage: ^9.2.4
  mime: ^2.0.0
  json_serializable: ^6.9.4
  awesome_notifications: ^0.10.1
  pedometer: ^4.0.2
  flutter_foreground_task: ^9.1.0
  shared_preferences: ^2.5.2
  flutter_animate: ^4.5.2
  icons_launcher: ^3.0.1
  table_calendar: ^3.2.0
  timezone: ^0.10.0
  wakelock_plus: ^1.3.2
  connectivity_plus: ^6.1.4
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/img/intro/
    - assets/img/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend/Lexend-Black.ttf
          weight: 900


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "logo/Logo_x_Obese.png"
  min_sdk_android: 21

icons_launcher:
  image_path: "logo/Logo_x_Obese.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#ffffff"
  image: logo/Logo_x_Obese_small.png
  color_dark: "#ffffff"
  image_dark: logo/Logo_x_Obese_small.png

  android_12:
    image: logo/Logo_x_Obese_small.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#ffffff"
