name: x_obese
description: "A new fitness app for bese"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^5.0.0-release-candidate-9.3.2
  toastification: ^3.0.1
  fluttertoast: ^8.2.12
  geolocator: ^13.0.2
  cached_network_image: ^3.4.1
  permission_handler: ^11.4.0
  geocoding: ^3.0.0
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  http: ^1.3.0
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  smooth_page_indicator: ^1.2.1
  hive_flutter: ^1.1.0
  pinput: ^5.0.1
  google_maps_flutter: ^2.10.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  fluentui_system_icons: ^1.1.273
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.70.2
  carousel_slider: ^5.0.0
  flutter_secure_storage: ^9.2.4
  internet_connection_checker_plus: ^2.7.1
  mime: ^2.0.0
  json_serializable: ^6.9.4
  awesome_notifications: ^0.10.1
  pedometer: ^4.0.2
  flutter_foreground_task: ^8.17.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/img/intro/
    - assets/img/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend/Lexend-Black.ttf
          weight: 900