List<Map> holidays = [
  {
    "date": "2026-02-04",
    "name": "Shab-e-Barat",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-02-21",
    "name": "Shaheed Day (International Mother Language Day)",
    "type": "National",
    "isSubjectToChange": false,
  },
  {
    "date": "2026-03-17",
    "name": "Shab-e-Qadr (Lailatul Qadr)",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-03-19",
    "name": "Eid ul-Fitr Holiday",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-03-20",
    "name": "Eid ul-Fitr / Jumu'atul-Wida",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-03-21",
    "name": "Eid ul-Fitr",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-03-22",
    "name": "Eid ul-Fitr Holiday",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-03-23",
    "name": "Eid ul-Fitr Holiday",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-03-26",
    "name": "Independence Day",
    "type": "National",
    "isSubjectToChange": false,
  },
  {
    "date": "2026-04-14",
    "name": "Pohela Boishakh (Bengali New Year)",
    "type": "Cultural",
    "isSubjectToChange": false,
  },
  {
    "date": "2026-05-01",
    "name": "May Day / Buddha Purnima",
    "type": "Public / Religious",
    "isSubjectToChange": false,
  },
  {
    "date": "2026-05-26",
    "name": "Eid ul-Adha Holiday",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-05-27",
    "name": "Eid ul-Adha Holiday",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-05-28",
    "name": "Eid ul-Adha",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-05-29",
    "name": "Eid ul-Adha Holiday",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-05-30",
    "name": "Eid ul-Adha Holiday",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-05-31",
    "name": "Eid ul-Adha Holiday",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-06-26",
    "name": "Ashura",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-08-05",
    "name": "July Mass Uprising Day",
    "type": "National",
    "isSubjectToChange": false,
  },
  {
    "date": "2026-08-26",
    "name": "Eid-e-Milad-un-Nabi",
    "type": "Religious",
    "isSubjectToChange": true,
  },
  {
    "date": "2026-09-04",
    "name": "Krishna Janmashtami",
    "type": "Religious",
    "isSubjectToChange": false,
  },
  {
    "date": "2026-10-21",
    "name": "Durga Puja (Vijayadashami)",
    "type": "Religious",
    "isSubjectToChange": false,
  },
  {
    "date": "2026-12-16",
    "name": "Victory Day",
    "type": "National",
    "isSubjectToChange": false,
  },
  {
    "date": "2026-12-25",
    "name": "Christmas Day",
    "type": "Religious",
    "isSubjectToChange": false,
  },
];
